#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Jeeyong Um
"""Emit docs/COVERAGE.md: which source every codepoint came from.

Reads `build/provenance.json`, which `scripts/build.py` writes from the glyph
names while they still carry the source prefix. It has to be recorded there
rather than read back out of `dist/`: ttfautohint regenerates every glyph name
as `uniXXXX`, so after hinting the binary no longer knows where its glyphs came
from.

Usage:  python3 scripts/coverage_table.py
"""

from __future__ import annotations

import collections
import sys

from fontTools.unicodedata import block

BASE = "Iosevka Term NF"
PROVENANCE = "build/provenance.json"

NOTE = {
    "Pretendard JP": "hangul, han, kana, CJK punctuation and fullwidth forms; "
                     "scaled per script onto the two-cell box",
    "M PLUS 1p": "brackets, 〇 〒 〓 〈 〉, halfwidth katakana, ￢ ￣ ￤",
    "Noto Sans KR": "enclosed, circled and squared forms; archaic jamo",
    BASE: "Latin, symbols, box drawing, Braille, Powerline, Nerd Fonts",
}


def main() -> None:
    import json
    prov = {int(k): v for k, v in json.load(open(PROVENANCE)).items()}

    per_block: dict[str, collections.Counter] = collections.defaultdict(
        collections.Counter)
    span: dict[str, list[int]] = {}
    for cp, src in prov.items():
        b = block(chr(cp))
        per_block[b][src] += 1
        lo, hi = span.get(b, (cp, cp))
        span[b] = (min(lo, cp), max(hi, cp))

    total = collections.Counter()
    for counts in per_block.values():
        total.update(counts)

    out = [
        "# Where every glyph comes from",
        "",
        "Generated by `scripts/coverage_table.py` from `build/provenance.json`,",
        "which the build writes while the glyph names still carry their source —",
        "so it records what the build actually produced, not what it intended.",
        "",
        f"**{sum(total.values())} codepoints** across **{len(per_block)} Unicode "
        "blocks**. The K and J faces differ only in which form 611 han take, so",
        "one table covers both.",
        "",
        "## By source",
        "",
        "| Source | Codepoints | What it draws |",
        "|---|---:|---|",
    ]
    for name, n in total.most_common():
        out.append(f"| {name} | {n} | {NOTE.get(name, '')} |")

    out += [
        "",
        "## By Unicode block",
        "",
        "| Block | Range | Codepoints | Source |",
        "|---|---|---:|---|",
    ]
    for b in sorted(per_block, key=lambda b: span[b][0]):
        lo, hi = span[b]
        counts = per_block[b]
        if len(counts) == 1:
            src = next(iter(counts))
        else:
            src = " + ".join(f"{s} {n}" for s, n in counts.most_common())
        out.append(f"| {b} | `U+{lo:04X}–U+{hi:04X}` | "
                   f"{sum(counts.values())} | {src} |")

    out += [
        "",
        "## Reading a mixed row",
        "",
        "A block with more than one source is one this build had to assemble.",
        "There are two reasons, and both are deliberate.",
        "",
        "**The primary source drew it for proportional setting.** Pretendard is",
        "an Inter-based proportional face and draws the brackets, `〈 〉` and the",
        "whole enclosed and squared range at advances the grid cannot take —",
        "698 to 3638 units against a cell of 1920. Squeezing those is distortion,",
        "not scaling, so they come from a CJK-native face instead. See",
        "[ADR 0013](adr/0013-the-width-table-must-cover-what-the-build-declares.md).",
        "",
        "**Unicode splits the block by width.** `Enclosed CJK Letters and Months`",
        "keeps 8 codepoints with the Latin base — `㉈`–`㉏`, U+3248–324F. Their",
        "`East_Asian_Width` is Ambiguous, so the provider reserves them **one**",
        "cell where the rest of the block gets two, and Iosevka already draws",
        "them for one cell. They are not an oversight: the grid, not the design,",
        "put them there. See PLAN.md D8.",
        "",
    ]
    with open("docs/COVERAGE.md", "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote docs/COVERAGE.md — {sum(total.values())} codepoints, "
          f"{len(per_block)} blocks")


if __name__ == "__main__":
    main()
